---
# tasks file for prepare_python
- name: Install epel-release, python3, python3-devel, libselinux-python3
  become: true
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - epel-release
    - python3
    - python3-devel
    - libselinux-python3
  vars:
    ansible_python_interpreter: /usr/bin/python2

- name: Install Python 3
  become: true
  yum:
    name: python3
    state: present
    update_cache: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2  
    
- name: Install pip for Python 3
  become: true
  command: python3 -m ensurepip
  args:
    creates: /usr/bin/pip3
    executable: /bin/bash

- name: Upgrade pip for Python 3
  become: true
  command: pip3 install --upgrade pip

- name: Install psycopg2 for Python 3
  pip:
    name: psycopg2
    executable: pip3
    state: present
